<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;

/**
 * Rewrites config/barangays.php from the PSA's PSGC data. The committed file is the offline copy,
 * so the app never calls the API at runtime; rerun this when PSA publishes a boundary change.
 */
class SyncBarangays extends Command
{
    protected $signature = 'psgc:barangays';

    protected $description = "Refresh Lingayen's barangay list from the PSGC API";

    /** Lingayen, Pangasinan (9-digit PSGC; Dagupan is the neighbouring 015518000). */
    private const MUNICIPALITY = '015522000';

    public function handle(): int
    {
        $response = Http::timeout(20)->retry(2, 500, throw: false)
            ->get('https://psgc.gitlab.io/api/cities-municipalities/'.self::MUNICIPALITY.'/barangays/');

        if (! $response->successful() || ! is_array($response->json())) {
            $this->error('PSGC API unavailable; config/barangays.php was left unchanged.');

            return self::FAILURE;
        }

        $barangays = collect($response->json())
            ->mapWithKeys(fn (array $row) => [$row['psgc10DigitCode'] ?? $row['code'] => $row['name']])
            ->sort()
            ->all();

        file_put_contents(config_path('barangays.php'), "<?php\n\n"
            ."// Lingayen, Pangasinan barangays keyed by 10-digit PSGC code.\n"
            ."// Generated by `php artisan psgc:barangays` on ".now()->toDateString()."; do not edit by hand.\n"
            .'return '.var_export($barangays, true).";\n");

        $this->info(count($barangays).' barangays written to config/barangays.php.');

        return self::SUCCESS;
    }
}
